# Generated by Django 3.1.2 on 2020-10-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='forname',
            field=models.CharField(default='Forname', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='NIckname', max_length=30),
            preserve_default=False,
        ),
    ]
