# Generated by Django 3.1.2 on 2020-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20201005_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortcut', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('minimum_players', models.PositiveSmallIntegerField()),
                ('maximum_players', models.PositiveSmallIntegerField()),
                ('GOG', models.BooleanField(default=False)),
                ('Steam', models.BooleanField(default=False)),
                ('Epic', models.BooleanField(default=False)),
                ('Windows', models.BooleanField(default=False)),
                ('Linux', models.BooleanField(default=False)),
                ('Coach', models.BooleanField(default=False)),
                ('LAN', models.BooleanField(default=False)),
                ('WAN', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('genre', models.ManyToManyField(to='voter.Genre')),
            ],
        ),
    ]
