# Generated by Django 3.1.2 on 2020-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20201005_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
