# Generated by Django 3.1.2 on 2020-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20201005_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='voter.Genre'),
        ),
    ]
