# Generated by Django 3.1.2 on 2020-10-05 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_auto_20201005_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.game')),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='games',
        ),
        migrations.AddField(
            model_name='poll',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=2)),
                ('game_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.gameposition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='games_positions',
            field=models.ManyToManyField(to='voter.GamePosition'),
        ),
    ]
