# Generated by Django 3.1.2 on 2020-10-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0008_auto_20201006_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(),
        ),
    ]
